### ISSUE TITLE
`signTypedData` not working with Signer

### ISSUE THREAD

**Issue by yssf-io** [Instadapp/avocado-sdk#11]
Hello, I am trying to use this SDK directly with an ethers `Wallet` signer, not a Metamask/WalletConnect signer.

But `signTypedData`, which is used when building the signature that will be broadcasted, only signs when a provider is given; I modified it on my end to make it work with a `Wallet` signer also.

I can make a PR with my fix if you want; I'm asking in case you had a specific reason to only do MM/WC signing.

Thanks for the project!

**Comment by KABBOUCHI** [comment]
Thank you for your interest and proposed fix! Please go ahead and submit the PR.
